<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDefaultContentItems>true</EnableDefaultContentItems>
  </PropertyGroup>
  <ItemGroup>
    <Content Include=".github\scripts\tests\invalid-naming\file.with.dots.schema.json" />
  </ItemGroup>
</Project>