name: Validate JSON Schema Definition

on: [push, pull_request]

jobs:
  validate-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 26

      - name: Install Dependencies
        run: npm install ajv ajv-formats ajv-keywords glob

      - name: Run Schema Validation
        env:
          SCHEMA_PATH: "**/*.schema.json"        # Supports  wildcards
          SCHEMA_VERSION: "draft2020"            # Options: 'draft7', 'draft2019', 'draft2020'
        run: node .github/scripts/validate-schemas.js